// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bpioxfqsuxvgbdyjjbhi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwaW94ZnFzdXh2Z2JkeWpqYmhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMTI4MTIsImV4cCI6MjA2Njc4ODgxMn0.zwaFKxowIWoVoNg8PsDS5-9os6oP-4i3SrMsZqTqwkA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);